# Generated by Django 5.1 on 2024-08-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodieapp', '0005_alter_meal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='in_stock',
            new_name='inStock',
        ),
    ]
